### ISSUE TITLE
Makara and sidekiq mysql in use

### ISSUE THREAD

**Issue by grossjo** [instacart/makara#133] opened 2016-09-14 18:26 UTC
Ruby version: 2.0
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.1.3
makara: 0.3.6

I've recently started integrating the makara gem, and noticed some strange behaviour.

```
ActiveRecord::StatementInvalid: Mysql2::Error: This connection is in use by:
```

An idea what could be causing this?

**Comment by simonmorley** [comment] 2016-12-14 17:51
I've had to stop using Maraka with Sidekiq completely. Not sure if there's a thread issue or wot yet...

Whole application came to a grinding halt, page faults hitting 1,000/s. Memory over-loaded.

General misery. Will investigate further later...

**Comment by bleonard** [comment] 2016-12-14 18:07
Sorry to hear that. We are not currently using Sidekiq. We've done some tests and it seemed ok, but the scale was more of a staging load. Will look into it when we get there.

**Comment by mnelson** [comment] 2016-12-14 18:09
Do you guys have an `establish_connection` call in your `Sidekiq.configure_server` block? I'm not using sidekiq + makara right now but that was the first thing that came to mind.

**Comment by simonmorley** [comment] 2016-12-14 18:14
Nope. Was that a ---> "you should add that" or.... you should not have that in your config??

```
rails_root = ENV['RAILS_ROOT'] || File.dirname(__FILE__) + '/../..'
rails_env = Rails.env || 'production'

require 'sidekiq'
require 'sidekiq-status'

sidekiq_config = YAML.load(ERB.new(File.read(rails_root + '/config/redis_server.yml')).result)

Sidekiq.configure_server do |config|
  config.redis = { :host => "#{sidekiq_config[rails_env]["write"]}"}
end

Sidekiq.configure_client do |config|
  config.redis = { :host => "#{sidekiq_config[rails_env]["write"]}"}
end

schedule_file = "config/scheduler.yml"

if File.exists?(schedule_file)
  Sidekiq::Cron::Job.load_from_hash! YAML.load_file(schedule_file)
end
```

I'm just confirming for sure that the issue WAS Makara ;) 

We have significant load on our Sidekiq servers but the problem was easy to simulate, with limited traffic...

I'm going to try and test locally also again since we're running in Kubernetes.

**Comment by mnelson** [comment] 2016-12-14 22:04
I believe you _should_ have that in your server block. I essentially treat it the same as a unicorn / puma fork.

**Comment by simonmorley** [comment] 2016-12-15 09:30
I'll whack that in today and report back with findings.

**Comment by paolodona** [comment] 2017-02-27 10:00
Hi guys / @simonmorley 
just checking if you have any findings / tips on how to configure Sidekiq to work well with Makara?

**Comment by jwg2s** [comment] 2017-06-08 14:19
@simonmorley also curious to hear about this, we're attempting to use makara/sidekiq and would love to hear what you found

**Comment by bleonard** [comment] 2018-03-05 04:36
Seems like maybe a duplicate of: https://github.com/taskrabbit/makara/issues/151

**Closed as completed by bleonard** 2018-03-05 04:36 UTC
