### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?): DELETE FROM `users`

### ISSUE THREAD

**Issue by TheWudu** [instacart/makara#128] opened 2016-08-18 06:42 UTC
Hi!

After upgrading from 0.2.2 to 0.3.6 i got this error when trying to remove all users during a test. I found the reason in the upgrade from 0.3.3 (working fine) to 0.3.4.rc1 where the url handling was added. 
Our database.yml does NOT use the url option. We use host, port, username, password...

As I currently haven't the time to investigate further, maybe you my have a look. 

We use jruby (1.7.x and 9.x.x.x) and active record (various versions).

Best regards,
Wudu

**Comment by bleonard** [comment] 2016-09-09 17:42
can you please send your database.yml and a snippet from the test causing the issue?

**Comment by ThomasKoppensteiner** [comment] 2016-10-17 16:03
Hi,

I have a similar issue like @TheWudu. It occurs when the DatabaseCleaner tries do clean the database at the beginning of the test run.

Snippet from the database.yml

```
test:
  adapter: makara_mysql2
  database: test

  makara:
    sticky_master:      true
    sticky_slave:       true
    blacklist_duration: 60
    verbose:            true
    master_ttl:         10

    port:     3306
    encoding: utf8

    connections:
      - name: db
        role: master
        host: localhost
        username: <user>
        password: <pwd>

      - name: dbslave01
        role: slave
        weight: 3
        host: localhost
        username: <user>
        password: <pwd>
```

**Comment by sarahdiendorfer** [comment] 2017-12-13 13:14
Hi, are there any updates on this? I have the same problem...

**Comment by bleonard** [comment] 2017-12-13 20:21
Is the stack from `ConnectionUrlResolver`  - that's the only URI iseei n the project. A failing test owuld be awesome, but at least a stack, please.

**Comment by sarahdiendorfer** [comment] 2017-12-14 10:33
Thanks for the fast response!

Here is the stack trace:

```
Randomized with seed 13685


Finished in 0.30255 seconds (files took 11.36 seconds to load)
0 examples, 0 failures

Randomized with seed 13685

URI::InvalidURIError: bad URI(is not URI?): DELETE FROM `sport_types`
                            split at /Users/<>/.rvm/rubies/jruby-9.1.9.0/lib/ruby/stdlib/uri/rfc3986_parser.rb:67
                            parse at /Users/sad/.rvm/rubies/jruby-9.1.9.0/lib/ruby/stdlib/uri/rfc3986_parser.rb:73
                            parse at /Users/sad/.rvm/rubies/jruby-9.1.9.0/lib/ruby/stdlib/uri/common.rb:227
                          env_for at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/rack-test-0.6.3/lib/rack/test.rb:193
                           delete at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/rack-test-0.6.3/lib/rack/test.rb:93
                           delete at /Users/sad/.rvm/rubies/jruby-9.1.9.0/lib/ruby/stdlib/forwardable.rb:189
                      public_send at org/jruby/RubyKernel.java:1810
          block in method_missing at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:106
          block in any_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:153
                 block in provide at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/pool.rb:105
                           handle at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/active_record/connection_adapters/makara_abstract_adapter.rb:37
                          provide at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/pool.rb:104
                   any_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:152
                   method_missing at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:104
         block in create_fixtures at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/activerecord-4.2.7.1/lib/active_record/fixtures.rb:529
                         each_key at org/jruby/RubyHash.java:1405
         block in create_fixtures at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/activerecord-4.2.7.1/lib/active_record/fixtures.rb:528
                             each at org/jruby/RubyArray.java:1734
         block in create_fixtures at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/activerecord-4.2.7.1/lib/active_record/fixtures.rb:524
             block in transaction at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213
           within_new_transaction at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184
                      transaction at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213
             block in transaction at (eval):61
                   _makara_hijack at (eval):15
                      transaction at (eval):57
                      public_send at org/jruby/RubyKernel.java:1810
                   method_missing at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/connection_wrapper.rb:99
             block in transaction at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:28
  block in appropriate_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/active_record/connection_adapters/makara_abstract_adapter.rb:160
  block in appropriate_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:173
                         hijacked at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:245
  block in appropriate_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:172
                 block in provide at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/pool.rb:105
                           handle at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/active_record/connection_adapters/makara_abstract_adapter.rb:37
                          provide at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/pool.rb:104
  block in appropriate_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:171
                 appropriate_pool at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:186
           appropriate_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:170
           appropriate_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/active_record/connection_adapters/makara_abstract_adapter.rb:159
             block in transaction at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:27
         block in create_fixtures at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/activerecord-4.2.7.1/lib/active_record/fixtures.rb:523
    disable_referential_integrity at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/activerecord-jdbc-adapter-1.3.22/lib/arjdbc/mysql/adapter.rb:315
                      public_send at org/jruby/RubyKernel.java:1810
                   method_missing at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/connection_wrapper.rb:99
                      public_send at org/jruby/RubyKernel.java:1807
          block in method_missing at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:106
          block in any_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:153
                 block in provide at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/pool.rb:105
                           handle at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/active_record/connection_adapters/makara_abstract_adapter.rb:37
                          provide at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/pool.rb:104
                   any_connection at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:152
                   method_missing at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/makara-0.3.9/lib/makara/proxy.rb:104
                  create_fixtures at /Users/sad/.rvm/gems/jruby-9.1.9.0/gems/activerecord-4.2.7.1/lib/active_record/fixtures.rb:508
```
The root cause is this method call:
`ActiveRecord::FixtureSet.create_fixtures("<project>/spec/fixtures", :user, {})`


Unfortunately I can't provide a failing test, because it doesn't even start the tests.

Thanks in advance!

**Comment by bleonard** [comment] 2017-12-17 17:38
I meant a test in the makara test suite.
Just looking at the stack, I can't figure out what URI we are even talking about.
Have an idea? is it something in your database.yml ?

**Comment by bleonard** [comment] 2018-03-05 04:39
Closing until there is an example.

**Closed as completed by bleonard** 2018-03-05 04:39 UTC
